---
- name: "Build and run Docker container with Ansible"
  hosts: localhost
  tasks:
    - name: Remove old container if it exists
      command: sudo docker stop ansi
      ignore_errors: yes

    - name: Remove old container
      command:  docker rm -f ansi
      ignore_errors: yes

    - name: Build Docker image from Dockerfile
      command: docker build -t ansible-img .

    - name: Tag the image
      command: docker tag ansible-img omarzaki222/python

    - name: Run container from ansible-img
      command: docker run -d --name ansi -p 5000:5000 ansible-img
    - name: Login to Docker Hub
      command: echo "{{ docker_hub_password }}" | docker login -u "{{ docker_hub_username }}" --password-stdin
      vars:
        docker_hub_username: "omarzaki222"  # Replace with your Docker Hub username
        docker_hub_password: "01118001235@ZzZ"    # Replace with your Docker Hub password

    - name: Push Docker image to Docker Hub
      command: docker push omarzaki222/python